project:
  type: website

website:
  site-url: "https://laverde97.github.io/latent-frontiers/"
  title: "Latent Frontiers"
  description: "Exploring AI, machine learning, medicine, and doctoral research at the frontiers of discovery."

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

      - text: "CV"
        href: cv.qmd

    right:
      - icon: github
        href: https://github.com/Laverde97

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true